name: Build and Deploy App to S3

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create .env file from GitHub Secrets
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_APP_KAKAOMAP_KEY=${{ secrets.VITE_APP_KAKAOMAP_KEY }}" >> .env
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Sync to S3 (upload to root)
        run: |
          aws s3 sync dist/ s3://rider.itseats.shop/ \
            --delete \
            --cache-control "no-cache" \
            --exact-timestamps
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
